### ISSUE TITLE
Code error when opening project in xcode

### ISSUE THREAD

**Issue by xiaohaizi90** [xuo-lynn/VisionOS-Smart-Image#1]
When I opened this project using xcode, multiple error messages appeared. How can I configure to ensure the program runs correctly? I want to implement a similar feature of this project through Vision Pro, which involves capturing images through a camera and identifying objects of interest. Unfortunately, as far as I know, the camera of Vision Pro cannot be accessed by developers outside of Apple. https://forums.developer.apple.com/forums/thread/732508
<img width="476" alt="info" src="https://github.com/xuo-lynn/VisionOS-Smart-Image/assets/46621443/3cf7f81b-1b8e-4cc7-a49b-26ffd8652198">

**Comment by xuo-lynn** [comment]
the camera stream isn't accessible for developers. this code is for when it does become accessible.
